-- MySQL Script generated by MySQL Workbench
-- Sun Apr 12 03:39:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema trueque_match_db
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TIPO_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TIPO_USUARIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_USUARIO` (
  `id_tipo_usuario` INT NOT NULL COMMENT 'Su número de identificación único (1, 2, 3...).',
  `nombre_tipo` VARCHAR(50) NOT NULL COMMENT 'El nombre del rol (Ej: \'estándar\', \'admin\').',
  `descripcion` TEXT NULL COMMENT 'Explicación de qué puede hacer ese rol.',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Default: CURRENT_TIMESTAMP.',
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT 'El número de socio único.',
  `nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre completo.',
  `correo` VARCHAR(150) NOT NULL COMMENT 'Email (único, no se repite).',
  `clave_acceso` VARCHAR(255) NOT NULL COMMENT 'La contraseña (seguridad).',
  `telefono` VARCHAR(15) NULL COMMENT 'Es opcional (SÍ nulo).',
  `ciudad` VARCHAR(100) NOT NULL COMMENT 'Es opcional.',
  `foto_perfil` VARCHAR(255) NULL COMMENT 'Link a la foto (opcional)',
  `reputacion` DECIMAL(3,2) NOT NULL COMMENT 'Default: 0.00. Son las \"estrellitas\" del usuario.',
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Default: NOW(). Cuándo se unió al club.',
  `activo` TINYINT(1) NULL DEFAULT 1 COMMENT 'Default: 1. (1=Sí, 0=No)',
  `id_tipo_usuario` INT NOT NULL COMMENT 'Conexión con la tabla anterior.',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  INDEX `fk_usuario_tipo_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `mydb`.`TIPO_USUARIO` (`id_tipo_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMINISTRADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ADMINISTRADOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ADMINISTRADOR` (
  `id_admin` INT NOT NULL AUTO_INCREMENT COMMENT 'El ID único del administrador.',
  `nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre completo del jefe.',
  `correo` VARCHAR(150) NOT NULL COMMENT 'Su email (debe ser único, UQ).',
  `clave_acceso` VARCHAR(255) NOT NULL COMMENT 'La contraseña protegida.',
  `nivel_acceso` VARCHAR(50) NOT NULL COMMENT 'Default: \'moderador\'. (Otras: \'super_admin\').',
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Default: CURRENT_TIMESTAMP.',
  `activo` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Default: 1 (Significa que está habilitado).',
  PRIMARY KEY (`id_admin`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OFERTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OFERTA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OFERTA` (
  `id_oferta` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único.',
  `titulo` VARCHAR(200) NOT NULL COMMENT 'Título descriptivo.',
  `descripcion` VARCHAR(45) NOT NULL COMMENT 'Detalles de lo ofrecido.',
  `categoria` ENUM('producto', 'servicio', 'conocimiento', 'experiencia') NOT NULL COMMENT 'Escribe: \'producto\',\'servicio\',\'conocimiento\',\'experiencia\'.',
  `estado` ENUM('activa', 'inactiva', 'intercambiada') NOT NULL DEFAULT 'Activa' COMMENT 'Default: \'activa\'. Opciones: \'activa\',\'inactiva\',\'intercambiada\'.',
  `imagen_url` VARCHAR(255) NULL COMMENT 'URL de la foto (Opcional).',
  `ciudad` VARCHAR(100) NULL COMMENT 'Ciudad del intercambio (Opcional).',
  `valor_estimado` DECIMAL(10,2) NULL COMMENT 'Valor de referencia en pesos.',
  `fecha_publicacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Default: NOW() o CURRENT_TIMESTAMP.',
  `id_usuario` INT NOT NULL COMMENT '¡Importante! Es el dueño de la oferta.',
  PRIMARY KEY (`id_oferta`),
  INDEX `fk_oferta_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_oferta_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRUEQUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TRUEQUE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TRUEQUE` (
  `id_TRUEQUE` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del negocio.',
  `estado` ENUM('pendiente', 'aceptado', 'completado', 'cancelado') NOT NULL DEFAULT 'pendiente','aceptado','completado','cancelado' COMMENT 'Opciones: \'pendiente\',\'aceptado\',\'completado\',\'cancelado\'.',
  `fecha_propuesta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Default: CURRENT_TIMESTAMP.',
  `fecha_trueque` DATETIME NULL COMMENT 'La fecha real cuando se entreguen las cosas.',
  `descripcion_acuerdol` TEXT NULL COMMENT 'Notas adicionales sobre el trato.',
  `id_usuario_propone` INT NOT NULL COMMENT 'El usuario que lanza la oferta.',
  `id_oferta_propone` INT NOT NULL COMMENT 'El producto/servicio que él pone.',
  `id_usuario_recibe` INT NOT NULL COMMENT 'El usuario que recibe la propuesta.',
  `id_oferta_recibe` INT NOT NULL COMMENT 'El producto/servicio que él entregará a cambio.',
  PRIMARY KEY (`id_TRUEQUE`),
  INDEX `fk_trueque_usuario_propone_idx` (`id_usuario_propone` ASC) VISIBLE,
  INDEX `fk_trueque_oferta_propone_idx` (`id_oferta_propone` ASC) VISIBLE,
  INDEX `fk_trueque_usuario_recibe_idx` (`id_usuario_recibe` ASC) VISIBLE,
  INDEX `fk_trueque_oferta_recibe_idx` (`id_oferta_recibe` ASC) VISIBLE,
  CONSTRAINT `fk_trueque_usuario_propone`
    FOREIGN KEY (`id_usuario_propone`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trueque_oferta_propone`
    FOREIGN KEY (`id_oferta_propone`)
    REFERENCES `mydb`.`OFERTA` (`id_oferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trueque_usuario_recibe`
    FOREIGN KEY (`id_usuario_recibe`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trueque_oferta_recibe`
    FOREIGN KEY (`id_oferta_recibe`)
    REFERENCES `mydb`.`OFERTA` (`id_oferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EVALUACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EVALUACION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EVALUACION` (
  `id_evaluacion` INT NOT NULL AUTO_INCREMENT COMMENT '(Automático)',
  `calificacion` INT NOT NULL COMMENT '(Aquí el usuario pone de 1 a 5)',
  `Comentario` TEXT NULL COMMENT '(Es opcional, por si quiere escribir algo)',
  `fecha_evaluacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CURRENT_TIMESTAMP',
  `id_usuario_evaluado` INT NOT NULL COMMENT '(El \"puerto\" para saber quién calificó)',
  `id_trueque` INT NOT NULL COMMENT '(El \"puerto\" para conectar al negocio)',
  PRIMARY KEY (`id_evaluacion`),
  INDEX `fk_evaluacion_trueque_idx` (`id_trueque` ASC) VISIBLE,
  INDEX `fk_evaluacion_usuario_idx` (`id_usuario_evaluado` ASC) VISIBLE,
  CONSTRAINT `fk_evaluacion_usuario`
    FOREIGN KEY (`id_usuario_evaluado`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_evaluacion_trueque`
    FOREIGN KEY (`id_trueque`)
    REFERENCES `mydb`.`TRUEQUE` (`id_TRUEQUE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SOLICITUD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SOLICITUD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SOLICITUD` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT COMMENT 'El ID de la petición.',
  `mensaje` TEXT NULL COMMENT 'Mensaje inicial del solicitante.',
  `estado` ENUM('pendiente', 'aceptada', 'rechazada') NOT NULL DEFAULT 'pendiente' COMMENT 'Estado de la solicitud.',
  `fecha_solicitud` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora en que se envía la solicitud.',
  `fecha_respuesta` DATETIME NOT NULL COMMENT 'Fecha en que se respondió la solicitud.',
  `id_usuario_solicita` INT NOT NULL COMMENT ' Usuario que envía la solicitud.',
  `id_usuario_recibe` INT NOT NULL COMMENT 'Usuario que recibe la solicitud.',
  `id_oferta` INT NOT NULL COMMENT 'Oferta sobre la que se hace la solicitud.',
  PRIMARY KEY (`id_solicitud`),
  INDEX `fk_solicitud_usuario_solicita_idx` (`id_usuario_solicita` ASC) VISIBLE,
  INDEX `fk_solicitud_oferta_idx` (`id_oferta` ASC) VISIBLE,
  INDEX `fk_solicitud_receptor_idx` (`id_usuario_recibe` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_solicitante`
    FOREIGN KEY (`id_usuario_solicita`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solicitud_receptor`
    FOREIGN KEY (`id_usuario_recibe`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solicitud_oferta`
    FOREIGN KEY (`id_oferta`)
    REFERENCES `mydb`.`OFERTA` (`id_oferta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOTIFICACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NOTIFICACION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NOTIFICACION` (
  `id_notificacion` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único de la notificación.',
  `mensaje` TEXT NOT NULL,
  `tipo` ENUM('info', 'alerta', 'sistema', 'trueque') NOT NULL DEFAULT 'info' COMMENT 'Tipo de notificación.',
  `leida` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Estado de lectura (0 = no leída, 1 = leída).',
  `fecha_envio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora de envío.',
  `id_usuario` INT NOT NULL COMMENT 'Usuario destinatario.',
  `id_trueque` INT NULL COMMENT 'Trueque relacionado (si aplica).',
  `id_oferta` INT NULL COMMENT 'Oferta relacionada (si aplica).',
  PRIMARY KEY (`id_notificacion`),
  INDEX `fk_notificacion_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_notificacion_trueque_idx` (`id_trueque` ASC) VISIBLE,
  INDEX `fk_notificacion_oferta_idx` (`id_oferta` ASC) VISIBLE,
  CONSTRAINT `fk_notificacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notificacion_trueque`
    FOREIGN KEY (`id_trueque`)
    REFERENCES `mydb`.`TRUEQUE` (`id_TRUEQUE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notificacion_oferta`
    FOREIGN KEY (`id_oferta`)
    REFERENCES `mydb`.`OFERTA` (`id_oferta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REPORTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`REPORTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`REPORTE` (
  `id_reporte` INT UNSIGNED NOT NULL,
  `motivo` ENUM('fraude', 'incumplimiento', 'comportamiento', 'otro') NULL COMMENT 'Motivo de la denuncia.',
  `descripcion` TEXT NOT NULL COMMENT 'Detalle del incidente.',
  `estado` ENUM('pendiente', 'revisado', 'resuelto') NOT NULL DEFAULT 'pendiente' COMMENT ' Estado del reporte.',
  `fecha_reporte` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT ' Fecha y hora del reporte.',
  `fecha_resolucion` DATETIME NULL COMMENT 'Fecha en que se resolvió.',
  `id_usuario_reporta` INT NOT NULL COMMENT 'FK → USUARIO(id_usuario) → Usuario que genera el reporte.',
  `id_usuario_reportado` INT NULL COMMENT ' FK → USUARIO(id_usuario) → Usuario denunciado.',
  `id_oferta` INT NULL COMMENT ' FK → OFERTA(id_oferta) → Oferta relacionada (si aplica).',
  `id_trueque` INT NULL COMMENT 'FK → TRUEQUE(id_trueque) → Trueque relacionado (si aplica).',
  PRIMARY KEY (`id_reporte`),
  INDEX `fk_reporte_usuario_reporta _idx` (`id_usuario_reporta` ASC) VISIBLE,
  INDEX `fk_reporte_usuario_reportado_idx` (`id_usuario_reportado` ASC) VISIBLE,
  INDEX `fk_reporte_oferta_idx` (`id_oferta` ASC) VISIBLE,
  INDEX `fk_reporte_trueque_idx` (`id_trueque` ASC) VISIBLE,
  CONSTRAINT `fk_reporte_usuario_reporta `
    FOREIGN KEY (`id_usuario_reporta`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reporte_usuario_reportado`
    FOREIGN KEY (`id_usuario_reportado`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reporte_oferta`
    FOREIGN KEY (`id_oferta`)
    REFERENCES `mydb`.`OFERTA` (`id_oferta`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reporte_trueque`
    FOREIGN KEY (`id_trueque`)
    REFERENCES `mydb`.`TRUEQUE` (`id_TRUEQUE`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO_OFERTA — Favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USUARIO_OFERTA — Favoritos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO_OFERTA — Favoritos` (
  `id_usuario` INT NOT NULL COMMENT 'Usuario que guarda la oferta como favorita.',
  `id_oferta` INT NOT NULL COMMENT 'Oferta marcada como favorita.\n\n',
  `fecha_guardado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora en que se guardó la oferta.',
  PRIMARY KEY (`id_usuario`, `id_oferta`),
  INDEX `fk_usuario_oferta_oferta_idx` (`id_oferta` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_oferta_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_oferta_oferta`
    FOREIGN KEY (`id_oferta`)
    REFERENCES `mydb`.`OFERTA` (`id_oferta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
